const actionTypes = {

    ADD_COURSE: "ADD_COURSE",
    DELETE_COURSE: "DELETE_COURSE",
    GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
    UPDATE_COURSE: "UPDATE_COURSE",
    GET_COURSES_SEARCH: "GET_COURSES_SEARCH",
};

export default actionTypes;
